runtime: nodejs18

handlers:
  - url: /www/assets/img
    static_dir: www/assets/img

  - url: /www/assets/css
    static_dir: www/assets/css

  - url: /www/assets/js
    static_dir: www/assets/js

  - url: /.* 
    static_files: www/index.html
    upload: www/index.html

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
